version: '3.0'
services:
    api:
        build:
            context: ./api
        environment:
            - HTTP_PORT=8081
        ports:
            - "8081:8081"
        networks:
            - personal
    view:
        build:
            context: ./view
        environment:
            - API_HOST=api
            - API_PORT=8081
            - NODE_ENV=production
        env_file:
            -   view/.env.local
        networks:
            - personal
        ports:
            - "80:8080"
            - "443:443"
networks:
    personal:
