version: '3.0'
services:
    api:
        image: drewjocham/api:latest
        networks:
            - personal
        ports:
            - "8081:8081"
    view:
        image: drewjocham/view:latest
        environment:
            - API_HOST=api
            - NODE_ENV=development
        networks:
            - personal
        ports:
            - "80:8080"
networks:
    personal:
