version: '3.0'
services:
    api:
        build:
            context: ./api
        environment:
            - PORT=8081
        ports:
            - "8081:8081"
        networks:
            - personal
    view:
        build:
            context: ./view
        environment:
            - API_HOST=api
            - API_PORT=8081
            - NODE_ENV=production
        env_file:
            -   view/.env.local
        networks:
            - personal
        ports:
            - "80:8080"
            - "443:443"
    postgres:
        container_name: postgres_container
        image: postgres:14.1
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
            - ./dbscripts/postgres:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: fullstackguru
        ports:
            - 5434:5432
networks:
    personal:
